name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    types: [opened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  autofix:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autofix.ci') }}
    runs-on: ubuntu-latest
    env:
      FIX_MODE: "${{ contains(github.event.pull_request.labels.*.name, 'autofix.ci') && 'fix' || 'check' }}"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
           python-version: '>=3.10'

      - name: "Run author update script"
        continue-on-error: true
        run: |
          python3 buildbot/update_authors.py

      - name: Commit and push if changed
        if: env.FIX_MODE == 'fix'
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          commit-message: '[autofix.ci] fix file authorship'
