name: Shamrock (Intel/LLVM)


on:
  workflow_call:
    inputs:
      light_ci:
        description: "Whether to run the light CI"
        required: true
        type: boolean

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      light_ci:
        description: "Whether to run the light CI"
        required: false
        default: false
        type: boolean


jobs:

  set_matrix:
    name: Set Intel/LLVM matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        shell: bash
        run: |
          if [[ "${{ inputs.light_ci }}" == "true" ]]; then
            cat > matrix.json <<'JSON'
          {
            "include": [
              {
                "machine": "docker.intel_oneapi",
                "container": "intel/oneapi",
                "runtest": false
              }
            ]
          }
          JSON
          else
            cat > matrix.json <<'JSON'
          {
            "include": [
              {
                "machine": "ci.intel-llvm.cuda",
                "container": "ghcr.io/shamrock-code/shamrock-ci:ubuntu22cuda12dpcpp",
                "runtest": false
              },
              {
                "machine": "ci.intel-llvm.rocm",
                "container": "ghcr.io/shamrock-code/shamrock-ci:ubuntu22rocm543dpcpp",
                "runtest": false
              },
              {
                "machine": "docker.intel_oneapi",
                "container": "intel/oneapi",
                "runtest": false
              }
            ]
          }
          JSON
          fi

          {
            echo "matrix<<EOF"
            cat matrix.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  shamrock_intel_llvm:
    name: Intel/llvm ${{ matrix.machine }}
    needs: [set_matrix]
    runs-on: [self-hosted,  docker-runner]

    container:
      image: ${{ matrix.container }}

    strategy:
      matrix: ${{ fromJSON(needs.set_matrix.outputs.matrix) }}

    timeout-minutes: 60
    steps:
      #### Checkout part ####
      # Checkout merge commit if PR otherwise default
      - name : Reconfigure git
        run:  |
          git config --global --add safe.directory '*'
          git config --global --list
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show diff against main
        if: github.event_name == 'pull_request_target'
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD
      #### End Checkout part ####

      - name: Setup env
        run : ./env/new-env --machine ${{ matrix.machine }} --builddir build --

      - name: Cat activate file
        shell: bash # In docker container github action default to sh
        run: |
          cat build/activate

      - name: Configure
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source ./activate && shamconfigure

      - name: Configure sham install
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source ./activate &&  \
            cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install_test

      - name: Build & install
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          export NINJA_STATUS="[%f/%t j=%r] "
          source ./activate && shammake install

      - name: Pull reference files
        run: |
          cd build
          git clone https://github.com/Shamrock-code/reference-files.git

      - name: run Shamrock help
        if: matrix.runtest
        run: |
          cd build
          ./shamrock --help
          ./shamrock --help --color

      - name: run Shamrock Test help
        if: matrix.runtest
        run: |
          cd build
          ./shamrock_test --help
          ./shamrock_test --help --color

      - name: run Shamrock Unittests world_size = 1
        if: matrix.runtest
        run: |
          cd build
          ./shamrock_test --color --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 2
        if: matrix.runtest
        run: |
          cd build
          mpirun --allow-run-as-root --bind-to socket:overload-allowed --oversubscribe -n 2 ./shamrock_test --color --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 3
        if: matrix.runtest
        run: |
          cd build
          mpirun --allow-run-as-root --bind-to socket:overload-allowed --oversubscribe -n 3 ./shamrock_test --color --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 4
        if: matrix.runtest
        run: |
          cd build
          mpirun --allow-run-as-root --bind-to socket:overload-allowed --oversubscribe -n 4 ./shamrock_test --color --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: Try starting Shamrock (installed version)
        shell: bash # In docker container github action default to sh
        if: matrix.runtest
        run: |
          cd build/install_test/bin
          ls ..
          LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./shamrock --smi --sycl-cfg 0:0
